// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhkfxkkflnpljwplsspo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoa2Z4a2tmbG5wbGp3cGxzc3BvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzOTU5NzYsImV4cCI6MjA1ODk3MTk3Nn0.GIQiB695PO7x3Yn_hFdt8hreR1RBTk1gTsY25Btodro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);